### ISSUE TITLE
Analisar- Página com Política de privacidade da ESP

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#267]
### **Objetivo**
**Como** usuária cadastrada no iSUS
**Quero** saber qual a Política de Privacidade
**Para** entender meus direitos e deveres

### **Contexto**
Com a aplicação da LGPD, precisamos deixar claro para o usuário do ISUS quais dados são exigidos dele e o que faremos com estes dados. Esta tarefa implementa a página que mostrará a Política de Privacidade.

### **UX**
- [x] Botão de voltar (setinha) no cabeçalho - ps: assim como aparece hoje uma vez que a usuária está na página 'Termos de uso'
- [x] Experiência - sugestão: deve ser possível acessar esta tela quando a usuária não está logada e clica no menu hambúrguer na home, abaixo de Termos de Uso
- [x] Experiência - sugestão: deve ser possível acessar esta tela quando a usuária está logada e clica no botão na página Meu Perfil, logo abaixo de Termos de uso, em 'Privacidade'
- [x] Experiência - essa página também está inserida no fluxo de cadastro, após a página do Termo de Uso
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606
- [x] Experiência - também é possível chegar na nesta página através das telas abaixo (tela inicial do ID saúde e de login), quando se clica no link
![image](https://user-images.githubusercontent.com/67436275/90191049-88e89c00-dd96-11ea-951c-001abff67033.png)
- [x] Botão de li e aceito quando a página é acessada no fluxo de cadastro
![image](https://user-images.githubusercontent.com/67436275/90045591-a558db80-dca5-11ea-95ba-2e7c0ac1310d.png)

Protótipo (original):
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606

### **Escopo**
- Criar página com Política de Privacidade
Texto provisório: https://docs.google.com/document/d/1VrxUCVIsemIcSWfkaqNHV_JPb5aAcmvXv86J2PGq1J0/edit
- Botão de voltar (setinha) no cabeçalho - ps: assim como aparece hoje uma vez que a usuária está na página 'Termos de Uso'
- Corrigir para maiúscula a palavra 'uso' presente em Termos de uso, localizada em Meu Perfil, logo abaixo de 'Privacidade'

### **Critérios de Aceitação**
- [x] Acesso pelo menu lateral
**Dado que** estou logada no iSUS
**Quando** acesso o menu lateral e clico em "Política de Privacidade"
**Então** sou redirecionada para a página correta

- [x] Acesso pelo menu lateral
**Dado que** não estou logada no iSUS
**Quando** acesso o menu lateral e clico em "Política de Privacidade"
**Então** sou redirecionada para a página correta

- [x] Voltar - menu lateral
**Dado que** acessei a política de privacidade pelo menu lateral
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a página de perfil

- [x] Voltar - ID Saúde
**Dado que** acessei a política de privacidade através da página inicial do ID Saúde
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a página inicial do ID Saúde

- [x] Acesso - login
**Dado que** cliquei no link da política de privacidade da página de login
**Quando** sou redirecionada para a página de política de privacidade
**Então** vejo o texto da política

- [x] Voltar - login
**Dado que** acessei a de política de privacidade através da página de login
**Quando** clico na seta de voltar no cabeçalho
**Então** sou redirecionada para a de login

Protótipo (original):
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606

**Comment by kurjes** [comment]
Aguardando o recebimento do texto referente a politica de privacidade do ID saúde.

pareando com @daianefreira

**Comment by jessica-salmazzo** [comment]
Vamos agendar uma conversa com uma pessoa que possui conhecimento claro sobre LGPD para conseguirmos esclarecer dúvidas sobre como devemos lidar e o que devemos implementar nas atividades de compartilhamento de dados/cadastros entre ID Saúde, Mapa da Saúde, iSUS, entre outras plataformas. 

Tendo essas questões esclarecidas, conseguimos seguir com o refinamento e detalhamento das estórias.

@Clarisse1983 está em contato para marcar a reunião.

**Comment by uira** [comment]
@jessica-salmazzo Já está elaborada, em processo de revisão.

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5560%3A0

Texto provisório (política de privacidade): https://docs.google.com/document/d/1VrxUCVIsemIcSWfkaqNHV_JPb5aAcmvXv86J2PGq1J0/edit
