### ISSUE TITLE
[BUGS- QA] Criar deeplink para redes sociais da seção "Sobre o SUS"

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-app#278]
### **Objetivo**
Redirecionar links de apps da seção "Sobre o SUS" para os aplicativos próprios, quando instalados

### **Contexto**
Na tarefa #262 adicionamos links de redes sociais na seção "Sobre o SUS" do app. Precisamos garantir que todos os links para redes sociais sejam direcionados para o app específico, quando este estiver instalado. Caso os apps não estejam instalados, o usuário deve ser redirecionado para o navegador padrão. 

Atualmente os apps estão abrindo conforme abaixo:
- IOS
    - Facebook - navegador padrão
    - Instagram - app instagram
    - Youtube - app youtube
    - Linkedin - app linkedin
    - Site - webview

- Android
    - Facebook - navegador padrão
    - Instagram - webview
    - Youtube - app youtube
    - Linkedin - webview
    - Site - webview

**-> Todos estes links devem ser abertos nos apps específicos ou no navegador no celular**

### **Escopo**
- [x] - Facebook - redirecionar para o app quando instalado, ou para o navegador padrão se não estiver instalado
- [x] Instagram - redirecionar para o app quando instalado, ou para o navegador padrão se não estiver instalado
- [x] linkedin - redirecionar para o app quando instalado, ou para o navegador padrão se não estiver instalado
- [x] site - aberto no navegador padrão

### **Critérios de Aceitação**
- [x] Facebook - app
**Dado que** eu tenho o app do facebook instalado
**Quando** clico no link do facebook da SESA ou da ESP
**Então** o app do facebook abre na página correta 

- [x] Facebook - navegador
**Dado que** eu não tenho o app do facebook instalado
**Quando** clico no link do facebook da SESA ou da ESP
**Então** o navegador padrão do meu celular abre na página correta

- [x] Instagram - app
**Dado que** eu tenho o app do Instagram instalado
**Quando** clico no link do Instagram da SESA ou da ESP
**Então** o app do Instagram abre na página correta 

- [x] Instagram - navegador
**Dado que** eu não tenho o app do Instagram instalado
**Quando** clico no link do Instagram da SESA ou da ESP
**Então** o navegador padrão do meu celular abre na página correta

- [x] Youtube - app
**Dado que** eu tenho o app do Youtube instalado
**Quando** clico no link do Youtube da ESP
**Então** o app do Youtube abre na página correta 

- [x] Youtube - navegador
**Dado que** eu não tenho o app do Youtube instalado
**Quando** clico no link do Youtube da ESP
**Então** o navegador padrão do meu celular abre na página correta

- [x] Linkedin - app
**Dado que** eu tenho o app do Linkedin instalado
**Quando** clico no link do Linkedin da ESP
**Então** o app do Linkedin abre na página correta 

- [x] Linkedin - navegador
**Dado que** eu não tenho o app do Linkedin instalado
**Quando** clico no link do Linkedin da ESP
**Então** o navegador padrão do meu celular abre na página correta

- [x] Site 
**Dado que** eu estou na página "SUS no Ceará"
**Quando** eu clico no link do site da ESP ou da SESA
**Então** o navegador padrão do meu celular abre na página correta

- [x] whats - app
**Dado que** eu tenho o whatsapp instalado
**Quando**eu clico no link do whatsapp da SESA
**Então** o app do WhatsApp é aberto numa nova conversa com a SESA

- [x] whats - navegador
**Dado que** eu não tenho o whatsapp intalado
**Quando** cliclo no link do whatsapp da sesa
**Então** então meu navegador é aberto no link correto

- [x] Plano de modernização
**Dado que** estou na página sobre a ESP
**Quando** clico no link do Plano de Modernização da Saúde
**Então** meu navegador padrão é aberto com o link correto
- [x] Links de Facebook, Instagram e Youtube redirecionando para o app/site **(IOS )**
Dentro da tela **SUS no Ceará**, que pode ser acessada através do menu lateral. 
**Comportamento atual:** Dentro das sessões **O  iSUS é ESP** e **A ESP é SESA** existem links que devem redirecionar para o facebook, instagram e youtube mas que ao serem clicados não acontece nada. 
**Comportamento esperado:** Ao serem clicados esses links devem redirecionar para o app caso o usuário tenha instalado  ou serem abertos no navegador padrão do usuário.

**Comment by ItaloRod** [comment]
Fiz meu teste do Deep Linking e no Android abriu corretamente, tanto os navegadores caso não exista nenhum app instalado. Caso tenha o app, abre o app corretamente.

No iOS, quando clico no instagram e no facebook nada acontece. Mesmo se eu tiver ou não aplicativo no seu sistema operacional. O Link do Youtube também não funcionou pra mim, estando instalando ou não.

**Comment by ItaloRod** [comment]
Realizamos todos os testes no iOS com todos os links das redes sociais, Todos abrem corretamente no app, com exceção do facebook que persiste em abrir no navegador.

**Comment by ilizakoski** [comment]
Finalizei a tarefa [#278](https://github.com/EscolaDeSaudePublica/isus-app/issues/278) com junto [#283](https://github.com/EscolaDeSaudePublica/isus-app/issues/283) e [#276](https://github.com/EscolaDeSaudePublica/isus-app/issues/276).
