### ISSUE TITLE
novos  banners para o carrossel da home

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#297]
### **Contexto**
Já temos a funcionalidade de carrossel de banner, nessa tarefa temos por objetivo alimentar esse carrossel com banners e links de redirecionamento. 

## **Escopo**
- [x] banner dos 30 anos do  SUS

- [x] banner do PPSUS

- [x] banner de cartilha de saúde mental

**Todos os banners e links de redirecionamento podem ser encontrados nesta planilha na aba Banner** : https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit?ts=5eaccb5c#gid=2004870043

## **Critérios de Aceitação**
- [x] acesso ao carrossel de banner
**Dado que** sou usuária do iSUS
**Quando** estou na home do app independente de estar logada  ou não 
**Então** visualizo o carrossel de banners 

- [x] banner sus 30 anos
**Dado que** estou na home
**Quando** clico no banner de 30 anos do SUS
**Então** sou redirecionada pera o link associado 

- [x] banner do PPSUS
**Dado que** estou na home
**Quando** clico no banner de PPSUS
**Então** sou redirecionada pera o link associado 

- [x] banner  de cartilha mental 
**Dado que** estou na home
**Quando** clico no banner de cartilha mental
**Então** sou redirecionada pera o link associado

**Comment by nicoledbianchin** [comment]
As imagens no dispositivo Android estavam com pouca qualidade. Fiz um commit que adiciona as imagens como .png que deve arrumar esse problema
