### ISSUE TITLE
Qualiquizz

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#327]
## **Contexto**

Como oportunidade de fornecer um serviço diferencial para os profissionais de saúde, surge a ideia de implantar o Qualiquiz dentro do iSUS, possibilitando que usuárias realizem testes para avaliarem seus conhecimentos em diversos temas conforme os quizes disponíveis. 

**Problema**
Para que o programa "Nascer Ceara" seja implantado, é premissa garantir que sejam envolvidos profissionais de saúde 
capacitados.  Para cumprir esta premissa, foi proposto uma avaliação dos profissionais de saúde. Após análise desta avaliação, serão disponibilizados cursos especializados para capacitação dos profissionais e viabilizar o projeto. 

**Premissas**
- Apenas usuárias cadastradas podem realizar o quiz
- O gatilho para chamada do qualiquiz será no banner

**Informações importantes**
- Desejável: 30/11
- Link do Qualiquiz: https://escoladesaudepublica.github.io/qualiquiz/
- Passar por parametro JWT

**Perguntas**
- Onde ele será apresentado?   
Banner
- Existe uma data limite para realização do quizz? Se sim, será barrado ao clicar no banner? 
O banner será retirado assim que o prazo para responder o quiz for finalizado. 
- Usuárias podem realizar o quizz somente uma vez? O que ocorre se clicar no banner e já tiver respondido o quizz? 
A usuaria será redirecionada para o qualiquiz e lá existirá um tratamento (api) para informar que o quiz já foi respondido e qual a nota da usuária (Criar card sobre isso)
- Existe algum retorno da nota do quizz via o iSUS? 
Sim, será responsabilidade api (Criar card)
- Quem terá acesso?  
O banner ficará disponível para todas, mas a realização do quiz somente será exibido para pessoas autenticadas
- Qual a jornada do usuário? 
Teremos jornada para pessoas cadastradas e nao cadastradas
- Como será o comportamento quando a usuária clicar no banner e ela não for cadastrada no iSUS?

**Não é escopo:**
- O quiz pode ser respondido por usuárias de qualquer categoria? Tem quiz específicos por categoria, mas não será realizado neste primeiro momento. 

## **Escopo**
- [] Criar banner para disponibilizar o qualiquiz
- [] Ao clicar no banner do quiz, será necessário verificar se a pessoa é cadastrada
- [] Criar webview para chamada do endpoint do qualiquizz, enviar o token do usuário (passar por parametro JWT)
- [] Redirecionar o usuário para 
- [] 
- []
- []
- []

**Comment by jessica-salmazzo** [comment]
Atividade duplicada com a #391. Finalizando essa para não deixar atividades duplicadas no backlog.
