### ISSUE TITLE
Realizar tagueamento Analytics fluxo de criação e adição de informações ao Perfil

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#345]
### **Objetivo**
**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

### **Contexto**
Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

### **Escopo**

- [x] Realizar o tagueamento do fluxo de criação de perfil que temos hoje no iSUS para visualizar os dados dentro do analytics

- [x] Planilha com o fluxo de tagueamentos: https://docs.google.com/spreadsheets/d/1w0f9KXDx0VhsFHb5xhFXURXAh6YGHIkORItdbVhLm4A/edit?usp=sharing

### **Critérios de aceite**

- [x] Simulação dos dados mapeados
**Dado** que não tenho cadastro no iSUS
**Quando** clico em Realizar meu cadastro 
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Perfil | Click | Iniciar meu cadastro)

- [x] Simulação dos dados mapeados
**Dado** que não tenho cadastro no iSUS
**Quando** finalizo os preenchimentos dos dados e clico em Finalizar 
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Perfil | Click | Finalizar meu cadastro)

- [x] Simulação dos dados mapeados
**Dado** que estou realizando meu cadastro de perfil no iSUS
**Quando** finalizo as seleções de categorias e setores e clico em Finalizar no final do cadastro
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Perfil | Cadastro | Cadastro {{categorias e setores selecionados}})

- [x] Simulação dos dados mapeados
**Dado** que estou realizando a edição das minhas informações profissionais do meu perfil no iSUS
**Quando** clico em editar informações
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Perfil | Click |Editar informações profissionais)

- [x] Enviar categorias e unidade de serviços na edição profissional
**Dado** que estou editando meu perfil profissional
**Quando** finalizo as seleções de categorias e setores e clico em Salvar 
**Então** no Analytics deve ficar registrado essa ação conforme tagueamento da planilha (Perfil | Atualização Cadastro | Cadastro {{categorias e setores selecionados}}) (OBSERVAÇÕES 2)

### **Links para ajudar**

- [ ] https://rnfirebase.io/analytics/screen-tracking

- [ ] https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- [ ] https://support.google.com/analytics/answer/1033068?hl=pt-br

### **Observações**
1. A implementação deve ser realizada nas plataformas de Android e iOS, e os testes devem ser executados em emuladores ou conforme for possível de acordo com a disponibilidade do recurso das plataformas. 

2. Ao salvar as alterações do formulário no cadastro e na edição deve-se seguir o seguinte modelo:

```javascript
const now = Date.now()
`cadastro_cp${cod_categoria_profissional}_${now}`
`cadastro_us${cod_unidade_servico}_${now}`
```

3. 
|Nome do evento | Ocorre na tela | Dispara em | Category | Action | Label |
|-- | -- | -- | -- | -- | --|
Perfil | Conteudo Inicial | Quando clica no botão de Realizar meu cadastro | Perfil | Click | iniciar_meu_cadastro
Perfil | Cadastro | Quando clica no botão de Finalizar | Perfil | Click | finalizar_meu_cadastro
Perfil | Cadastro | Quando clica no botão de Finalizar | Perfil | Cadastro | cadastro_<categorias e setores selecionados>
Perfil | Cadastro | Quando clica no botão Editar Informações para informações profissionais | Perfil | Click | editar_informacoes_profissionais
Perfil | Cadastro | Quando clica no botão Salvar para informações profissionais | Perfil | Atualização Cadastro | cadastro_<categorias e setores selecionados>
