### ISSUE TITLE
Adcionar tags do Analytics Aba Educação Permanente

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#353]
# Objetivo

**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

# Contexto

Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

# Escopo

- [x] Enviar tag de Analytics `educacao_permanente` na `HOME` quando **clicar** no ícone de `EDUCAÇÃO PERMANETE`
- [x] Enviar tag de Analytics `educacao_permanente_cursos_online` na tela `EDUCAÇÃO PERMANETE` quando **clicar** na aba `CURSOS ONLINE`
- [x] Enviar tag de Analytics `educacao_permanente_tutoriais` na tela `EDUCAÇÃO PERMANETE` quando **clicar** na aba `TUTORIAIS`
- [x]  Enviar tag de Analytics `educacao_permanente_trilhas_de_formacao` na tela `EDUCAÇÃO PERMANETE` quando **clicar** na aba `TRILHAS DE FORMAÇÃO`
- [x] Enviar tag de Analytics `educacao_permanente_cartilhas` na tela `EDUCAÇÃO PERMANETE` quando **clicar** na aba `CARTILHAS`
- [x] Enviar tag de Analytics `educacao_permanente_documentos` na tela `EDUCAÇÃO PERMANETE` quando **clicar** na aba `DOCUMENTOS`

# Critérios de aceite

- [x] Tela Home -> Educação Permanente
**Dado** que estou na tela HOME
**Quando** clico em Educação Permanete
**Então** chamo a função de enviar para o analytics passando a label: educacao_permanente

- [x] Tela Educação Permanente -> Cursos Online
**Dado** que estou na tela Educação Permanente
**Quando** clico na aba Cursos Online
**Então** chamo a função de enviar para o analytics passando a label: educacao_permanente_cursos_online

- [x] Tela Educação Permanente -> Tutoriais
**Dado** que estou na tela Educação Permanente
**Quando** clico na aba Tutorias
**Então** chamo a função de enviar para o analytics passando a label: educacao_permanente_tutoriais

- [x] Tela Educação Permanente -> Trilhar de Formação
**Dado** que estou na tela Educação Permanente
**Quando** clico na aba Trilhas de Formação
**Então** chamo a função de enviar para o analytics passando a label: educacao_permanente_trilhas_de_formacao

- [x] Tela Educação Permanente -> Cartilhas
**Dado** que estou na tela Educação Permanente
**Quando** clico na aba Cartilhas
**Então** chamo a função de enviar para o analytics passando a label: educacao_permanente_cartilhas

- [x] Tela Educação Permanente -> Documentos
**Dado** que estou na tela Educação Permanente
**Quando** clico na aba Documentos
**Então** chamo a função de enviar para o analytics passando a label: educacao_permanente_documentos

# **Observações**

## **Links para ajudar**

- https://rnfirebase.io/analytics/screen-tracking
- https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br
- https://support.google.com/analytics/answer/1033068?hl=pt-br

## Extras
- A implementação deve ser realizada nas plataformas de Android e iOS, e os testes devem ser executados em emuladores ou conforme for possível de acordo com a disponibilidade do recurso das plataformas. 
- [Tabela de referência](https://docs.google.com/spreadsheets/d/1RK72eAKW7GWSYaebjO1Bv1om3rzt2E4FQUoeoo4Zo1c/edit?usp=sharing)

Nome do evento | Ocorre na tela | Dispara em | Category | Action | Label
-- | -- | -- | -- | -- | --
Home | Educação | Quando clica em Educação | Home | Click | educacao_permanente
Educação | Cursos Online | Quando clica em Cursos online em Educação | Educação | Click | educacao_permanente_cursos_online
Educação | Tutoriais | Quando clica em Tutoriais em Educação | Educação | Click | educacao_permanente_tutoriais
Educação | Trilhas de formação | Quando clica em Trilhas de formação em Educação | Educação | Click | educacao_permanente_trilhas_de_formacao
Educação | Cartilhas | Quando clica em Cartilhas em Educação | Educação | Click | educacao_permanente_cartilhas
Educação | Documentos | Quando clica em Documentos em Educação | Educação | Click | educacao_permanente_documentos

**Comment by Laysacunha** [comment]
Analytics já estava sendo enviado, mas não de acordo com os critérios de aceite. Havia uma duplicação no envio da Categoria Home e uma chamada com erro por haver um caractere especial. Critérios de aceite atendidos e duplicação resolvida.
