### ISSUE TITLE
Realizar tagueamento Analytics fluxo de exclusão da conta

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#360]
### **Objetivo**
**Como** pessoa responsável pela evolução contínua do app iSUS
**Quero** poder visualizar e analisar os dados gerados no iSUS de forma fácil e rápida
**Para** tomar a melhor decisão e ter indícios baseados em dados do que precisa ser evoluído no app. 

### **Contexto**
Implementamos o recurso Analytics no app iSUS para alcançarmos o objetivo de colher cada vez mais dados de nossas usuárias para nos auxiliar na tomada de decisões referente à evolução do app. Com isso, surge a necessidade de implementação de novos mapeamentos do comportamento de nossas usuárias que ainda não estão mapeadas. 

Dessa forma, essa atividade tem objetivo de continuar na evolução dos tagueamentos das áreas ainda não monitoradas pelo Analytics no app iSUS. 

### **Escopo**

- [x] Realizar o tagueamento do iSUS para visualizar os dados dentro do analytics

- [x] Planilha com o fluxo de tagueamentos:  

Nome do evento | Ocorre na tela | Dispara em | Category | Action | Label
-- | -- | -- | -- | -- | --
Excluir Conta | Perfil | Quando clica Excluir Conta | Perfil | Click | iniciar_exclusao_conta
Excluir Conta | Perfil | Quando clica em Voltar em Excluir Conta | Perfil | Click | cancelar_exclusao_conta 
Excluir Conta | Perfil | Quando clica em Excluir Conta na confirmação da exclusão da conta | Perfil | Click | confirmar_exclusao_conta
Excluir Conta | Perfil | Quando clica em Excluir em Excluir Conta | Perfil | Click | solicitar_confirmacao_exclusao_conta

### **Critérios de aceite**

- [x] 1. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Meu perfil
**Quando** clico em Excluir Conta
**Então** garantir que a função do Analytics é executada

- [x] 2. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Meu perfil
**Quando** clico em Excluir em Excluir Conta
**Então** garantir que a função do Analytics é executada

- [x] 3. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Meu perfil
**Quando** clico em Voltar em Excluir Conta
**Então** garantir que a função do Analytics é executada

- [x] 4. Simulação dos dados mapeados
**Dado** que acesso o iSUS no Meu perfil
**Quando** clico em Excluir Conta em Excluir Conta
**Então** garantir que a função do Analytics é executada

### **Links para ajudar**

- https://rnfirebase.io/analytics/screen-tracking

- https://developers.google.com/analytics/devguides/collection/analyticsjs/events?hl=pt-br

- https://support.google.com/analytics/answer/1033068?hl=pt-br,

### **Observações**

- A implementação deve ser realizada nas plataformas de Android e iOS, e os testes devem ser executados em emuladores ou conforme for possível de acordo com a disponibilidade do recurso das plataformas. 

- para não perder https://docs.google.com/spreadsheets/d/1q7OexQ9S4gNkD3bvhKukLIGCdGdUARzlOcR72EvfReY/edit#gid=53222801
