### ISSUE TITLE
Definir experiência para informar usuária sobre falha de internet e erro 404

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-app#384]
> Atividade foi editada e e será dividida

### **Objetivo**
**Como** usuária do iSUS 
**Quero** ser informada quando informações não são carregadas devido à falta de internet 
**Para** ter uma experiência melhor com o aplicativo

### **Contexto**
Atualmente, a usuária pode ter sua experiência comprometida quando não tem acesso à internet e esse cenário não é tão claro para ela no momento, visto que não temos uma mensagem visual explicando o que aconteceu e o que ela pode tomar de ação. 

Para tornar essa tarefa mais completa, fizemos o esforço de elencar todas as telas onde é possível existir ausência de internet e assim implementar a jornada de falta de conexão.

### **UX**
- [x] Criar experiência para falta de internet
- [x] Criar experiência para erros retornados da API
- [x] Criação da tela de mensagem de erro explicando a falha com a internet e o que a usuária pode realizar no momento

### **Escopo**
- [x] Elencar telas que podem necessitar desse tratamento
- [x] Implementar tela informando à usuária que houve falha de conexão com a internet de acordo com o tipo de página (verificar protótipo)
- [x] Implementar ação de voltar à página anterior ou sair da mensagem dada
- [x] Implementar ação de Tentar novamente com limite (3x)
- [x] Implementar tela de "Tente mais tarde" após a terceira tentativa de recarga sem sucesso

### **Telas e Cenários Mapeados**
- [x] Força-tarefa Anticorona > Boletins
- [x] Força-tarefa Anticorona > Notificação de casos
- [x] Força-tarefa Anticorona > Farmaco-vigilância
- [x] Força-tarefa Anticorona > Notas Técnicas
- [x] Força-tarefa Anticorona > Central de Ventiladores
- [x] Força-tarefa Anticorona > Denúncias
- [x] Aba Minha Saúde > Medidas de Proteção 
- [x] Alterar alguma aba em Minha Saúde para Minha Saúde > Saúde Mental
- [x] Alterar alguma aba em Minha Saúde para Minha Saúde > Bem-Estar Físico
- [x] Aba Educação > Cursos On-Line 
- [x] Alterar alguma aba em Educação para Educação > Tutoriais
- [x] Alterar alguma aba em Educação para Educação > Trilhas de Formação
- [x] Alterar alguma aba em Educação para Educação > Cartilhas
- [x] Alterar alguma aba em Educação para Educação > Documentos 
- [x] Aba Pesquisa > Epidemiologia 
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Saúde do Profissional
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Saúde Pública
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Quadro Clínico
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Manejo Clínico
- [x] Alterar alguma aba em Pesquisa para Pesquisa > Bases e Periódicos 
- [x] Cenários de realizar uma pesquisa pelo ícone de lupa
- [x] Cenário de enviar solicitação pelo Fale Conosco 
- [x] Cenário de realizar cadastro de perfil 
- [x] Cenário de Esqueci minha senha 
- [x] Cenário de Editar informações pessoais 
- [x] Cenário de Editar informações profissionais 
- [x] Cenário de Meus Conteúdos ao acessar seus cards

### **Critérios de Aceitação**
- [x] 1. Tela de mensagem de erro em conteúdos de APIs ou webviews
**Dado que** sou usuária do iSUS
**E** estou sem acesso à internet 
**Quando** tento acessar algum conteúdo disponível via API ou webview
**Então** a tela informando que estou sem acesso à internet deve ser exibida

- [x] 2. Tela de mensagem de erro de conexão em formulários
**Dado que** sou usuária do iSUS e tenho cadastro
**E** estou sem acesso à internet
**Quando** tento enviar um formulário
**Então** a modal informando que estou sem acesso à internet deve ser exibida

- [x] 3. Botão "tentar novamente" em mensagens de erro de conexão em APIs ou webviews
**Dado que** sou usuária do iSUS 
**E** estou sem acesso a internet
**Quando** clico no botão "tentar novamente" da mensagem de erro 
**Então** deve ser feita uma nova requisição para verificar minha conexão e tentar acessar o conteúdo

- [x] 4. Botão "tentar novamente" em mensagens de erro de conexão em formulários
**Dado que** sou usuária do iSUS 
**E** estou sem acesso a internet
**Quando** clico no botão "tentar novamente" da mensagem de erro 
**Então** deve ser feita uma nova requisição para que verificar minha conexão e tentar enviar o formulário novamente

- [x] 5. Conexão indisponível (terceira tentativa do botão "tentar novamente")
**Dado que** sou usuária do iSUS 
**E** estou sem acesso a internet
**Quando** clico no botão "tentar novamente" da mensagem de erro de conexão pela terceira vez
**Então** a tela de conexão indisponível deve ser exibida, informando que estou sem acesso à internet e devo tentar mais tarde

- [x] 6. Botão "Voltar" em mensagens de erro de conexão
**Dado que** sou usuária do iSUS
**E** estou em uma tela/modal de erro de conexão
**Quando** aciono o botão "Voltar"
**Então** sou direcionada para a última tela que visualizei com sucesso

- [x] 7. Botão "Voltar" em mensagens de conexão indisponível
**Dado que** sou usuária do iSUS
**E** estou em uma tela de indisponibilidade de conexão (exibida após tentar recarregá-la pela terceira vez)
**Quando** aciono o botão "Voltar"
**Então** sou direcionada para a tela principal do iSUS

### **Observações**

- Tela de exemplo do Dialog/Modal de tentar novamente [figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=4203%3A237)

![image](https://user-images.githubusercontent.com/6399202/116099806-b8b8a500-a682-11eb-8465-3c83e5bfaadd.png)

- Quando estiver sem conexão nas páginas demais páginas:

![image](https://user-images.githubusercontent.com/6399202/116100190-14832e00-a683-11eb-8962-49cfee11e65a.png)

- Após 3 tentativas falhas exibir a tela de sem conexão:

![image](https://user-images.githubusercontent.com/6399202/116100009-e9004380-a682-11eb-9e09-0dbd36daf69d.png)

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=5290:8053

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=5290:8053

**Comment by chicaothiago** [comment]
Dividir e conquistar esta issue
 Formulário:
- [x] Login
- [ ] Cadastro
- [ ] Cadastro ID Saúde
- [ ] Edição Pessoal
- [ ] Edição Profissional
- [ ] Feedback

- [X] Webviews:

Bottom Bars
- [ ] Minha Saúde
- [ ] Acadêmico
- [ ] Lab
