### ISSUE TITLE
QualiQuiz MVP1

### ISSUE THREAD

**Issue by daianefreira** [EscolaDeSaudePublica/isus-app#391]
## **Contexto**

Como oportunidade de fornecer um serviço diferencial para os profissionais de saúde, surge a ideia de implantar o Qualiquiz dentro do iSUS, possibilitando que usuárias realizem testes para avaliarem seus conhecimentos em diversos temas conforme os quizes disponíveis. 

**Problema**
Para que o programa "Nascer Ceara" seja implantado, é premissa garantir que sejam envolvidos profissionais de saúde 
capacitados.  Para cumprir esta premissa, foi proposto uma avaliação dos profissionais de saúde. Após análise desta avaliação, serão disponibilizados cursos especializados para capacitação dos profissionais e viabilizar o projeto. 

**Premissas**
- Apenas usuárias cadastradas podem realizar o quiz
- O gatilho para chamada do qualiquiz será no banner

**Informações importantes**
- Desejável: 30/11
- Link do Qualiquiz: https://escoladesaudepublica.github.io/qualiquiz/
- Passar por parametro JWT

**Perguntas**
- Onde ele será apresentado?   
Em um card na seção de **Serviços**
- Existe uma data limite para realização do quizz? Se sim, será barrado ao clicar no banner? 
Não foi definida data limite.
- Usuárias podem realizar o quizz somente uma vez? O que ocorre se clicar no banner e já tiver respondido o quizz? 
Não há limite para a realização do quiz.
- Existe algum retorno da nota do quizz via o iSUS? 
Sim, a API irá retornar o resultado do quiz que será exibido no projeto do QualiQuiz.
- Quem terá acesso?  
Todas as pessoas poderão visualizar o card do QualiQuiz, mas somente pessoas cadastras poderão responder ao quiz.
- Qual a jornada do usuário? 
Teremos jornada para pessoas cadastradas
- Como será o comportamento quando a usuária clicar no banner e ela não for cadastrada no iSUS?
Será rediorecionada para uma tela em que será solicitada a relização do cadastro.

**Não é escopo:**
- O quiz pode ser respondido por usuárias de qualquer categoria? 
Tem quiz específicos por categoria, mas não será realizado neste primeiro momento. 

## **Escopo**
- [x] Criar banner para disponibilizar o qualiquiz
- [x] Ao clicar no banner do quiz, será necessário verificar se a pessoa é cadastrada
- [x] Criar webview para chamada do endpoint do qualiquizz, enviar o token do usuário (passar por parametro JWT)
- [x] Redirecionar o usuário para o quiz
