### ISSUE TITLE
Integrar experiência de usuários no ID Saude( Front)

### ISSUE THREAD

**Issue by luisfcosta2015** [EscolaDeSaudePublica/isus-app#453]
## **Objetivo**

**Como** Pessoa usuária do iSUS que já tem cadastro dentro do ID Saude  
**Quero** me logar no app do iSUS.
**Para** conseguir acessar os recursos do app.

## **Contexto**

Uma vez que uma pessoa usuária tenta se logar no app do iSUS a partir de sua identidade já registrada no ID Saude, o app do iSUS não corresponde conforme necessário contendo todas as exigências de cadastros previamente configuradas pelo isus. Desta forma, se faz necessário a criação das telas complementares para que o app do iSUS avise a pessoa usuária que na primeira vez que ela efetua esta operação de login, será necessário que ela complemente algumas informações específicas deste app(iSUS). 

## **UX**
- [x] Definir experiência de integração entre dados do id saúde e isus no momento do login/cadastro
- [x] Definir fluxo de telas
- [x] Desenhar telas com experiência definida

## **Escopo**

- [x] Implementar a nova tela de login com o design do ID Saúde.
- [x] Sendo o primeiro acesso da pessoa usuária cadastrada primeiramente no ID Saúde, redirecionar para a página de introdução ao cadastro no iSUS.
- [x] Se a pessoa usuária não completar o cadastro o login não é efetuado por completo. Mantem-se deslogado.
- [x] O formulário de cadastro terão os dados do ID Saúde já preenchidos: E-mail e Nome.
- [x] Ao completar o cadastro, redirecionar para a HOME com a pessoa usuária logada.

## **Fora de Escopo**

- Alterar tela de cadastro já existente

## **Critérios de Aceitação**

- [x] Novo design da página de acesso  
**Dado que** não efetuei login  
**Quando** clico em MEU PERFIL e acesso a página de login    
**então** nova tela de acesso contendo a logo do ID Sáude

- [x] Novo design da página de formulário acesso  
**Dado que** estou na página de cadastro ou login
**Quando** clico no botão para efetuar o login  
**então** o formulário de login está com o design do ID Saúde

- [x] E-mail não inserido  
**Dado que** estou na tela do formulário de acesso  
**Quando** não insiro um e-mail  
**então** botão de acessar está desativado

- [x] E-mail invalido  
**Dado que** estou na tela do formulário de acesso  
**Quando** insiro um e-mail inválido
**então** botão de acessar está desativado e uma mensagem de e-mail inválido é exibida

- [x] Senha não inserida
**Dado que** estou na tela do formulário de acesso  
**Quando** não insiro uma senha
**então** botão de acessar está desativado

- [x] Senha invalida
**Dado que** estou na tela do formulário de acesso  
**Quando** insiro uma senha somente com espaços
**então** botão de acessar está desativado e uma mensagem de senha inválido é exibida

- [x] Exibir tela de introdução informando cadastro de dados obrigatórios
**Dado que** efetuo login com os dados corretos, cadastrados no ID Saúde  
**Quando** é o primeiro acesso no iSUS  
**então** tela introdutória informando que um cadastro de outras informações será necessário 

- [x] Continuar para cadastro de dados obrigatórios
**Dado que** efetuo login com os dados corretos, cadastrados no ID Saúde e estou na tela introdutória
**Quando** clico em continuar  
**então** exibir formulário para cadastro de informações obrigatórias no iSUS, com os campos do ID Saúde preenchidos.

- [x] Invalidar CPF já cadastrado
**Dado que** estou na tela de cadastro de informações pessoais
** Quando** digito um CPF já cadastrado no sistema
**Então** bloquear botão de continuar e exibir mensagem de CPF já cadastrado.

- [x] Bloquear edição de e-mail no formulário se já estiver preenchido
**Dado que** estou na tela de cadastro de informações pessoais
** Quando** tenho o campo de E-MAIL já previamente preenchido (vulgo modo edição)
**Então** bloquear a edição do campo

- [x] Desabilitar botão próximo caso dados não preenchidos ou inválidos
**Dado que** estou na tela de cadastro de dados pessoais
**Quando** não preencho os campos ou insiro dado incorreto  ee
**então** o botão continuar deve estar desativado.

- [x] Concluir cadastro
**Dado que** preencho o formulário por completo e estou na tela de cadastro de dados profissionais
**Quando** clico em concluir  
**então** atualizar a pessoa usuária e encaminhar para a tela de sucesso.

- [x] Atualizar contexto de login na tela de sucesso
**Dado que** conclui o cadastro da pessoa usuária
**Quando** estou na tela de sucesso  
**então** atualizar o contexto do aplicativo para login true

- [x] Atualizar loca storage o status de login na tela de sucesso
**Dado que** conclui o cadastro da pessoa usuária
**Quando** estou na tela de sucesso  
**então** salvar no storage o status de login true

- [x] Redirecionar para HOME após um tempo na tela de sucesso
**Dado que** conclui o cadastro da pessoa usuária
**Quando** estou na tela de sucesso  
**então** redirecionar para home após 4 segundos.   

# Observações

https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=5699%3A2

![fluxo_login_novo_isus_idsaude](https://user-images.githubusercontent.com/6399202/108852237-1a498e00-75c4-11eb-80e0-89f8080d9d37.png)

**Comment by wforte88** [comment]
Fluxos para análise disponíveis no [Figma](https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=5702%3A1401).

**Comment by MayaraMonte** [comment]
Protótipo atualizado: https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/?node-id=5699%3A2

**Comment by Wanderley97** [comment]
Todos os critérios de aceitação foram atendidos conforme teste em Moto G9 Power.
