### ISSUE TITLE
Problema de App Tracking Transparency

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#521]
# Descrição

Na ultima atualização da Apple, tornou-se obrigatória a utilização desta opção.
Quando houve o feedback da avaliação da Apple (na integra nas observações), comentou-se que o fato de estarmos solicitando campos pessoais em telas de cadastro/pré-cadastro torna-se necessária a solicitação de coleta dos dados das pessoas usuárias.

# Passo-a-passo para replicar

Deploy

# Ideia de solução

- [x] Ler a documentação de App Tracking Transparency
- [x] Instalar o pacote [react-native-tracking-transparency](https://github.com/mrousavy/react-native-tracking-transparency) e configurar a solicitação nas telas de pre-cadastro/cadastro somente quando for iOS.
- [ ] Se não for permitido o uso, redirecionar para a HOME e exibir uma notificação de que não foi dado acesso a coleta dos dados.

# Observações

## Texto Original

1 de jul de 2021 às 09:28
De Apple

5. 1.2 Legal: Privacy - Data Use and Sharing
Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing

The app privacy information you provided in App Store Connect indicates you collect data in order to track the user, including Physical Address, Phone Number, Performance Data, Other Contact Info, Name, Email Address, Other User Content, Demographics (race, religion, etc.), Sensitive Info, Precise Location, Device ID, Customer Support, User ID, Other Data Types, Other Usage Data, Crash Data, Other Diagnostic Data, and Product Interaction. However, you do not use App Tracking Transparency to request the user's permission before tracking their activity.

Starting with iOS 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them. This requirement protects the privacy of App Store users.

Next Steps

Here are two ways to resolve this issue:

- If you do not currently track, or decide to stop tracking, update your app privacy information 
in [App Store Connect](https://help.apple.com/app-store-connect/#/dev1b4647c5b). You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.

- If you track users, you must implement [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency) and request permission 
before collecting data used to track. When you resubmit, indicate in the Review Notes
where the permission request is located.

Resources

- Tracking is linking data collected from your app with third-party data for advertising purposes, 
or sharing the collected data with a data broker. Learn more about tracking.
- See Frequently Asked Questions about the new requirements for apps that track users.
- Learn more about designing appropriate permission requests.

---

**Comment by oxechicao** [comment]
Problema para gerar o build, erro ao executar o comando de compilação. Provavelmente é a falta de memória livre.

![image](https://user-images.githubusercontent.com/6399202/126988473-548b7c68-c100-48eb-bec0-cb0d1a6247c4.png)

**Comment by oxechicao** [comment]
# O que o ATT pode impedir de funcionar no aplicativo?

- Cadastro
  - Pré-cadastro IDSaúde
  - Cadastro 100%
- Analytics?
- Login?
