### ISSUE TITLE
Aplicar condicional para a função de analytics para não executar quando App Track está desabilitado.

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/isus-app#534]
# Objetivo

**Como** pessoa gestora da qualidade do iSUS
**Quero** quando o App Track desabilitador, bloquear a execução do Analytics
**Para** não ferir a permissão decidida pela pessoa usuária

# Contexto

Sempre que executar a função de analytics, caso a permissão do App Track não tenha sido habilitada, não executar a função de enviar ao Analytics.

# Escopo

- [ ] Com o App Track desabilitado, não executar as funções de enviar o analytics
- [ ] Com o App Track habilitado, executar o analytics normalmente

# Fora de Escopo

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Não enviar o analytics
**Dado que** estou com App Track desabilitado
**Quando** chamar a função de envio para o analytics
**Então** não executar

- [ ] Não enviar o analytics
**Dado que** estou com App Track habilitar
**Quando** chamar a função de envio para o analytics
**Então** executar normalmente

# Observações

Referência:  #521
